---
zabbix_server_volume_dir: "/opt/docker/zabbix_server"

netbox_services:
  [
    {
      name: zabbix-active,
      port: 10051,
      protocol: "tcp"
    },
    {
      name: zabbix-webui,
      port: 80,
      protocol: "tcp"
    }
  ]
