---
zabbix_server_volume_dir: "/opt/docker/zabbix_server"
zabbix_server: "testserver1.bartok.thouars.nl"

zabbix_mysql_user: "zabbix"
zabbix_mysql_database: "zabbix"


netbox_services:
  [
    {
      name: zabbix-active,
      port: 10051,
      protocol: "tcp"
    },
    {
      name: zabbix-webui,
      port: 80,
      protocol: "tcp"
    }
  ]


ping_hosts:
  [
    {
      name: ap-meterkast,
      ip: 192.168.55.200
    },
    {
      name: ap-zolder,
      ip: 192.168.55.201
    },
    {
      name: ap-woonkamer,
      ip: 192.168.55.202
    },
    {
      name: ap-kamer-eric,
      ip: 192.168.55.203
    }
  ]
