---
- name: Create directory for persistent volume
  file:
    path: "{{ influxdb_volume_dir }}"
    state: directory


- name: Create docker-compose.yml file from template
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ influxdb_volume_dir }}/docker-compose.yml"


- name: Create but do not start the docker stack
  docker_compose:
    project_src: "{{ influxdb_volume_dir }}"
    state: present
    stopped: true


- name: Add influxdb service to VM config in Netbox
  include_role:
    name: config_netbox_service_create
