---
- name: Load in general docker variables
  include_vars: "vars/docker_general.yml"


- name: Load in general secret variables
  include_vars: "vars/secrets.yml"


- name: Create base directory
  file:
    path: "{{ zabbix_server_volume_dir }}"
    state: directory


- name: Create directory for persistent volume
  file:
    path: "{{ zabbix_server_volume_dir }}/mysql"
    state: directory


- name: Create docker-compose.yml file from template
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ zabbix_server_volume_dir }}/docker-compose.yml"


- name: Start the docker stack
  docker_compose:
    project_src: "{{ zabbix_server_volume_dir }}"
    state: present


- name: Add zabbix service to VM config in Netbox
  include_role:
    name: config_netbox_service_create


# - - - - - - - - - - - - - - - - - - - - - - - -
#
# First execution of the playbook will lead to an error.
# Manual login to the zabbix server is required to finish the zabbix setup
# After that, restart this playbook
#
# To do: automate this step :)
#
- name: Message for first time execution
  debug:
    msg: "On the first run the playbook will stop here. Log in to the zabbix server and then restart the playbook"


- name: Create host groups
  local_action:
    module: community.zabbix.zabbix_group
    server_url: "http://{{ zabbix_server }}"
    login_user: "Admin"
    login_password: "{{ zabbix_password }}"
    state: present
    host_groups:
      - "Ping only hosts"
      - "Raspberry Pi"


- name: Set Admin user timezone
  local_action:
    module: community.zabbix.zabbix_user
    server_url: "http://{{ zabbix_server }}"
    login_user: "Admin"
    login_password: "{{ zabbix_password }}"
    alias: "Admin"
    usrgrps:
      - "Zabbix administrators"
    timezone: "Europe/Amsterdam"


# - - - - - - - - - - - - - - - - - - - - - - - -
#
# Import templates
#
- name: Import proxmox template
  local_action:
    module: community.zabbix.zabbix_template
    server_url: "http://{{ zabbix_server }}"
    login_user: "Admin"
    login_password: "{{ zabbix_password }}"
    template_xml: "{{ lookup('file', 'zabbix-pve-api.xml') }}"
    state: present


- name: Import pfsense active template
  local_action:
    module: community.zabbix.zabbix_template
    server_url: "http://{{ zabbix_server }}"
    login_user: "Admin"
    login_password: "{{ zabbix_password }}"
    template_xml: "{{ lookup('file', 'template_pfsense_active.xml') }}"
    state: present


- name: Import Synology template
  local_action:
    module: community.zabbix.zabbix_template
    server_url: "http://{{ zabbix_server }}"
    login_user: "Admin"
    login_password: "{{ zabbix_password }}"
    template_xml: "{{ lookup('file', 'template_synology_diskstation.yaml') }}"
    state: present


# - - - - - - - - - - - - - - - - - - - - - - - -
#
# Add hosts
#
- name: Add ping-only hosts
  local_action:
    module: community.zabbix.zabbix_host
    server_url: "http://{{ zabbix_server }}"
    login_user: "Admin"
    login_password: "{{ zabbix_password }}"
    host_name: "{{ item.name }}"
    host_groups:
      - "Ping only hosts"
    link_templates:
      - "ICMP Ping"
    status: enabled
    state: present
    inventory_mode: disabled
    interfaces:
      - type: agent
        main: 1
        useip: 1
        ip: "{{ item.ip }}"
        port: "10050"
  with_items: "{{ ping_hosts }}"


- name: Add proxmox host
  local_action:
    module: community.zabbix.zabbix_host
    server_url: "http://{{ zabbix_server }}"
    login_user: "Admin"
    login_password: "{{ zabbix_password }}"
    host_name: "hm80"
    host_groups:
      - "PVE Node"
    link_templates:
      - "Template pve api datacenter"
    status: enabled
    state: present
    inventory_mode: disabled
    interfaces:
      - type: agent
        main: 1
        useip: 1
        ip: "127.0.0.1"
        port: "10050"
    macros:
      - macro: "{$PVESERVER}"
        value: "hm80.bartok.thouars.nl"
      - macro: "{$PVETOKENID}"
        value: "{{ proxmox_zabbix_api_id }}"
      - macro: "{$PVESECRET}"
        value: "{{ proxmox_zabbix_api_token }}"


- name: Add pfsense host
  local_action:
    module: community.zabbix.zabbix_host
    server_url: "http://{{ zabbix_server }}"
    login_user: "Admin"
    login_password: "{{ zabbix_password }}"
    host_name: "pfsense"
    host_groups:
      - "Templates/Operating systems"
    link_templates:
      - "Template pfSense Active"
      - "Template pfSense Active IPsec"
    status: enabled
    state: present
    inventory_mode: disabled
    interfaces:
      - type: agent
        main: 1
        useip: 0
        dns: "pfsense.bartok.thouars.nl"
        port: "10050"


- name: Add Synology DS218 host
  local_action:
    module: community.zabbix.zabbix_host
    server_url: "http://{{ zabbix_server }}"
    login_user: "Admin"
    login_password: "{{ zabbix_password }}"
    host_name: "DS218"
    host_groups:
      - "Templates"
    link_templates:
      - "Synology DiskStation"
    status: enabled
    state: present
    inventory_mode: disabled
    interfaces:
      - type: snmp
        main: 1
        useip: 0
        dns: "ds218.bartok.thouars.nl"
        port: "161"

