---
- name: Create directory for persistent volume postgres data
  file:
    path: "{{ postgres_dir }}"
    state: directory


- name: Create directory for persistent volume redis data
  file:
    path: "{{ redis_dir }}"
    state: directory


- name: Create directory for persistent volume media files
  file:
    path: "{{ media_dir }}"
    mode: "o+w"
    state: directory


- name: Create netbox-docker repository directory
  file:
    path: "{{ netbox_docker_dir }}"
    state: directory


- name: Clone netbox-docker repository
  git:
    repo: https://github.com/netbox-community/netbox-docker.git
    accept_hostkey: true
    dest: "{{ netbox_docker_dir }}"
    version: release
    force: true


- name: Create docker-compose.override.yml file from template
  template:
    src: "docker-compose.override.yml.j2"
    dest: "{{ netbox_docker_dir }}/docker-compose.override.yml"


- name: Start the docker stack
  docker_compose:
    project_src: "{{ netbox_docker_dir }}"
    state: present


- name: Wait for netbox to startup
  wait_for:
    port: 80
    delay: 60


- name: Add http web ui services to VM config in Netbox
  include_role:
    name: config_netbox_service_create
