---
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
#       O L Y M P O S
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- name: Playbook to backup olympos
  hosts: olympos
  become: true

  vars_files:
    - roles/docker_influxdb/vars/main.yml
    - roles/docker_hostscanner/vars/main.yml
    - roles/docker_grafana/vars/main.yml
    - roles/docker_uptime-kuma/vars/main.yml
    - roles/docker_heimdall/vars/main.yml


  tasks:

    - name: Backup hostscanner container
      include_role:
        name: backup_docker_volume
      vars:
        volume_folder: "{{ hostscanner_volume_dir }}"
        compose_folder: "{{ hostscanner_volume_dir }}"
        stop_for_backup: false


    - name: Backup influxdb container
      include_role:
        name: backup_docker_volume
      vars:
        volume_folder: "{{ influxdb_volume_dir }}"
        compose_folder: "{{ influxdb_volume_dir }}"
        stop_for_backup: true


    - name: Backup grafana container
      include_role:
        name: backup_docker_volume
      vars:
        volume_folder: "{{ grafana_volume_dir }}"
        compose_folder: "{{ grafana_volume_dir }}"
        stop_for_backup: false


    - name: Backup uptime-kuma container
      include_role:
        name: backup_docker_volume
      vars:
        volume_folder: "{{ uptime_kuma_volume_dir }}"
        compose_folder: "{{ uptime_kuma_volume_dir }}"
        stop_for_backup: false

