---
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
#       P I N D O S
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- name: Playbook to backup pindos
  hosts: pindos
  become: true

  vars_files:
    - roles/docker_portainer/vars/main.yml
    - roles/docker_homepage/vars/main.yml


  tasks:

    - name: Backup portainer container
      include_role:
        name: backup_docker_volume
      vars:
        volume_folder: "{{ portainer_volume_dir }}"
        stop_for_backup: true
        compose_folder: "{{ portainer_volume_dir }}"


    - name: Backup homepage container
      include_role:
        name: backup_docker_volume
      vars:
        volume_folder: "{{ homepage_volume_dir }}"
        stop_for_backup: true
        compose_folder: "{{ homepage_volume_dir }}"


    - name: Backup secret files
      include_role:
        name: backup_secrets
      vars:
        projects_dir: "~{{ ansible_user }}"

