---
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
#       R O D O P I
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- name: Playbook to backup rodopi
  hosts: rodopi
  become: true

  vars_files:
    - roles/docker_nodered/vars/main.yml
    - roles/docker_open-webui/vars/main.yml


  tasks:

    - name: Backup nodered container
      include_role:
        name: backup_docker_volume
      vars:
        volume_folder: "{{ nodered_volume_dir }}"
        stop_for_backup: false
        compose_folder: "{{ nodered_volume_dir }}"


    - name: Backup Open WebUI container
      include_role:
        name: backup_docker_volume
      vars:
        volume_folder: "{{ open_webui_volume_dir }}"
        stop_for_backup: false
        compose_folder: "{{ open_webui_volume_dir }}"

