---
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
#       R O D O P I
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- name: Playbook to backup rodopi
  hosts: rodopi

  vars_files:
    - ../roles/docker_nodered/vars/main.yml


  tasks:

    - name: Backup nodered container
      include_role:
        name: backup_docker_volume
      vars:
        volume_folder: "{{ nodered_volume_dir }}"
        stop_for_backup: false
        compose_folder: "{{ nodered_volume_dir }}"
        ansible_become: true

