---
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
#       R O D O P I
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- name: Playbook to backup rodopi
  hosts: rodopi

  tasks:

    - name: Backup nodered container
      include_role:
        name: backup_docker_volume
      vars:
        volume_folder: "/opt/docker/nodered"
        stop_for_backup: false
