---
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
#       O L Y M P O S
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- name: Playbook to configure the host "olympos"
  hosts: olympos
  gather_facts: true


  vars:
    - zabbix_host_groups:
        - "Linux servers"
        - "Ping only hosts"
        - "LXC containers"

    - zabbix_templates:
        - "ICMP Ping"
        - "Linux by Zabbix agent"


  tasks:

    - include_role:
        name: docker
      vars:
        ansible_become: true   # install as root

    - include_role:
        name: config_portainer_endpoint_create

    - include_role:
        name: docker_influxdb

    - include_role:
        name: docker_grafana

    - include_role:
        name: docker_hostscanner

    - include_role:
        name: config_hostscanner_entry_create

    - include_role:
        name: docker_speedtest2influx

    - include_role:
        name: docker_heimdall

