---
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
#       T R A C C A R
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- name: Playbook to configure the host "traccar"
  hosts: traccar

  # wait with gathering facts until host is up and running
  # fact gathering will be done in role " basic_lxc"
  gather_facts: true


  tasks:

    - include_role:
        name: config_hostscanner_entry_create

    - include_role:
        name: traccar
