---
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
#       T A Y G E T O S  -  DMZ host
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- name: Playbook to configure the host "taygetos"
  hosts: taygetos
  gather_facts: true


  tasks:

    - include_role:
        name: docker
      vars:
        ansible_become: true   # install as root

    - include_role:
        name: config_portainer_endpoint_create

    - include_role:
        name: config_hostscanner_entry_create

    - include_role:
        name: docker_acme_dns

    - include_role:
        name: docker_traccar

