---
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
#         Play book to configure Raspberry Pi as NUT Server (Network UPS Tools)
#
#
#   Let op: playbook eerste keer aanroepen met argument --ask-pass omdat de 
#           public key van user "eric" dan nog niet bekend is.
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- name: Playbook om een Raspberry Pi als NUT Server te configureren
  hosts:
    - NUT_Server
  become: true


  vars_files:
    - vars/secrets.yml


  tasks:

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    #
    #   Initialize the Pi
    #
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    - name: Ensure public key is in users .ssh/authorized_keys
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ item }}"
      with_file:
        - ~/.ssh/id_rsa.pub


    - name: Make sure all packages are up-to-date
      apt:
        upgrade: dist
        update_cache: true


    - name: Set timezone to Europe/Amsterdam
      timezone:
        name: Europe/Amsterdam


    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    #
    #   Configure system monitoring
    #
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    - include_role:
        name: config_hostscanner_entry_create

    #- include_role:
    #    name: pi_telegraf


    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    #
    #   Install packages and backup config files
    #
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    - name: Installeer benodigde packages
      apt:
        name:
          - nut
          - nut-server
          - nut-client
          - apache2
          - nut-cgi
        state: present


    - name: Create backup folder for original config files
      file:
        path: /etc/nut/original_configs
        state: directory
        mode: '0755'
      register: no_backup_yet


    - name: Get a list of all nut config files
      find:
        paths: /etc/nut
        patterns: "*.conf"
      register: files_to_move
      when: no_backup_yet.changed


    - name: Move original configs to backup folder
      command: "mv {{ item.path }} /etc/nut/original_configs"
      with_items: "{{ files_to_move.files }}"
      when: files_to_move.files is defined


    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    #
    #   Create config files from templates
    #
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -




