---
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
#         P Y R G O S 
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- name: Playbook om een ansible developemnt systeem op te tuigen
  hosts: pyrgos
  become: true


  tasks:
    - name: Make sure all packages are up-to-date
      apt:
        upgrade: dist
        update_cache: true


    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    #
    #         Install generic tools
    #
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    - name: Installeer algemene (ontwikkel) tools
      apt:
        name:
          - git
          - tree
          - python3-pip
          - python3-venv
          - cifs-utils
          - net-tools
          - inetutils-ping
          - wireguard
          - snmp
          - snmp-mibs-downloader
          - unzip
        state: present

    - name: Installeer tools om repositories toe te voegen
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present


    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    #
    #         Download and install synology MIB files
    #
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    - name: Download Synology MIB file
      get_url:
        url: "https://global.download.synology.com/download/Document/Software/DeveloperGuide/Firmware/DSM/All/enu/Synology_MIB_File.zip"
        dest: "/root"
      register: download_MIB

       
    - name: Extract MIB file to root folder
      unarchive:
        remote_src: true
        src: "~/Synology_MIB_File.zip"
        dest: "/root"
      when: download_MIB.changed | bool


    - name: Copy MIB files to correct folder
      copy: 
        remote_src: true
        src: "/root/Synology_MIB_File/"
        dest: "/usr/share/snmp/mibs"
      when: download_MIB.changed | bool


    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    #
    #         D O C K E R
    #
    #         Install docker/docker-compose and clone docker git repository
    #
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    - include_role:
        name: docker

    - include_role:
        name: config_portainer_endpoint_create

    - name: Create docker directory
      file:
        path: "~{{ ansible_user }}/docker"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Clone docker repository
      git:
        repo: git@github.com:TeamDorus/docker.git
        accept_hostkey: true
        dest: "~{{ ansible_user }}/docker"
        clone: true
        update: true
      vars:
        ansible_become: false   # clone as {{ ansible_user }}


    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    #
    #         A N S I B L E
    #
    #         Install ansible and clone ansible GIT repository and related secrets files
    #
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    - name: Installeer alle files uit de .ssh directory voor ansible_user
      copy:
        src: "~{{ ansible_user }}/.ssh/"
        dest: "~{{ ansible_user }}/.ssh/"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: preserve


    - name: Installeer .gitconfig file voor ansible_user
      copy:
        src: "~{{ ansible_user }}/.gitconfig"
        dest: "~{{ ansible_user }}/.gitconfig"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: preserve

    - name: Installeer ansible
      apt:
        name:
          - ansible
          - sshpass             # in case you want to use password based ssh login
          - python3-proxmoxer
          - python3-pynetbox
        state: present

    - name: Installeer ansible collection for netbox
      command: /usr/bin/ansible-galaxy collection install netbox.netbox
      vars:
        ansible_become: false   # install as {{ ansible_user }}


    - name: Installeer ansible utils collection
      command: /usr/bin/ansible-galaxy collection install ansible.utils
      vars:
        ansible_become: false   # install as {{ ansible_user }}


    - name: Installeer ansible collection for zabbix
      command: /usr/bin/ansible-galaxy collection install community.zabbix
      vars:
        ansible_become: false   # install as {{ ansible_user }}


    - name: Create ansible directory
      file:
        path: "~{{ ansible_user }}/ansible"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Clone ansible repository
      git:
        repo: git@github.com:TeamDorus/ansible.git
        accept_hostkey: true
        dest: "~{{ ansible_user }}/ansible"
        clone: true
        update: true
      vars:
        ansible_become: false   # clone as {{ ansible_user }}

    - name: Copy ansible vault secrets.yml
      copy:
        src: "~{{ ansible_user }}/.ansible/secrets.yml"
        dest: "~{{ ansible_user }}/.ansible/secrets.yml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'

    - name: Copy ansible vault password file
      copy:
        src: "~{{ ansible_user }}/.ansible/passwd.txt"
        dest: "~{{ ansible_user }}/.ansible/passwd.txt"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'


    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    #
    #         T E R R A F O R M
    #
    #         Install terraform and clone terraform GIT repository and related secrets files
    #
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    - name: Voeg terraform apt-key toe
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg


    - name: Voeg terraform repo toe
      apt_repository:
        repo: deb [arch=amd64] https://apt.releases.hashicorp.com jammy main

    - name: Installeer terraform
      apt:
        name: terraform
        state: present
        update_cache: true


    - name: Create terraform directory
      file:
        path: "~{{ ansible_user }}/terraform"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Clone terraform repository
      git:
        repo: git@github.com:TeamDorus/terraform.git
        accept_hostkey: true
        dest: "~{{ ansible_user }}/terraform"
        clone: true
        update: true
      vars:
        ansible_become: false   # clone as {{ ansible_user }}

    - name: Copy terraform secrets pw
      copy:
        src: "~{{ ansible_user }}/terraform/secret_vars_pw"
        dest: "~{{ ansible_user }}/terraform/secret_vars_pw"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'
        decrypt: false          # do not decrypt the vault file

    - name: Copy terraform secrets api
      copy:
        src: "~{{ ansible_user }}/terraform/secret_vars_api"
        dest: "~{{ ansible_user }}/terraform/secret_vars_api"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'
        decrypt: false          # do not decrypt the vault file


    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    #
    #         F L A S K
    #
    #         Clone flaskapp GIT repository and related secrets files
    #
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    - name: Create flaskapp directory
      file:
        path: "~{{ ansible_user }}/flaskapp"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Clone flaskapp repository
      git:
        repo: git@github.com:TeamDorus/flaskapp.git
        accept_hostkey: true
        dest: "~{{ ansible_user }}/flaskapp"
        clone: true
        update: true
      vars:
        ansible_become: false   # clone as {{ ansible_user }}

    # - name: Create virtual environment for flaskapp
    #   pip:
    #     requirements: "~{{ ansible_user }}/flaskapp/flask/requirements.txt"
    #     virtualenv: "~{{ ansible_user }}/flaskapp/flask/venv"
    #     virtualenv_command: "python3 -m venv"
    #   vars:
    #     ansible_become: false   # create as {{ ansible_user }}

    - name: Copy .env file with api keys etc
      copy:
        src: "~{{ ansible_user }}/flaskapp/flask/.env"
        dest: "~{{ ansible_user }}/flaskapp/flask/.env"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'






