---
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
#       N E T B O X
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- name: Playbook to configure the host "netbox"
  hosts: netbox
  gather_facts: true


  tasks:

    - include_role:
        name: docker
      vars:
        ansible_become: true   # install as root


    - include_role:
        name: config_portainer_endpoint_create


    - name: Install git to clone the netbox repository
      apt:
        name:
          - git
      vars:
        ansible_become: true   # install as root


    - include_role:
        name: docker_netbox
