---
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
#         Play book to configure Raspberry Pi as NUT Server (Network UPS Tools)
#
#
#   Let op: playbook eerste keer aanroepen met argument --ask-pass omdat de 
#           public key van user "eric" dan nog niet bekend is.
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- name: Playbook om een Raspberry Pi als NUT Server te configureren
  hosts:
    - nutserver
  become: true


  vars_files:
    - vars/secrets.yml


  tasks:

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    #
    #   Initialize the Pi
    #
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    - name: Ensure public key is in users .ssh/authorized_keys
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ item }}"
      with_file:
        - ~/.ssh/id_rsa.pub


    - name: Make sure all packages are up-to-date
      apt:
        upgrade: dist
        update_cache: true


    - name: Set timezone to Europe/Amsterdam
      timezone:
        name: Europe/Amsterdam


    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    #
    #   Setup NUT Server
    #
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    - include_role:
        name: nutserver


    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    #
    #   Configure system monitoring
    #
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    - include_role:
        name: docker

    - include_role:
        name: config_hostscanner_entry_create

    - include_role:
        name: docker_telegraf

    - include_role:
        name: config_portainer_endpoint_create


    - name: Add NetBox tags to the device
      netbox.netbox.netbox_device:
        netbox_url: "{{ netbox_api_url }}"
        netbox_token: "{{ netbox_api_token }}"
        data:
          name: "{{ ansible_hostname }}"
          tags: 
          - ansible
          - docker
          - "{{ ansible_distribution }}-{{ ansible_distribution_release }}"
        state: present
      delegate_to: localhost
      when: ansible_facts['virtualization_role'] != "guest"
