---
- name: Playbook to configure the host "testserver1"
  hosts: testserver1

  # wait with gathering facts until host is up and running
  # fact gathering will be done in role " basic_lxc"
  gather_facts: true

  vars_files:
    - "~/.ansible/secrets.yml"

#  vars:
#    netbox_services: [{name: checkmk webui, port: 8000, protocol: "tcp"}]

  become: true

  tasks:

#    - include_role:
#        name: docker
#      vars:
#        ansible_become: true   # install as root


#    - include_role:
#        name: config_portainer_endpoint_create

    - include_role:
        name: docker_telegraf

#    - include_role:
#        name: config_netbox_service_create


#    - include_role:
#        name: config_hostscanner_entry_create


    - name: Add NetBox tags to the virtual machine
      netbox.netbox.netbox_virtual_machine:
        netbox_url: "{{ netbox_api_url }}"
        netbox_token: "{{ netbox_api_token }}"
        data:
          name: "{{ ansible_hostname }}"
          tags: 
          - ansible
          - docker
          - "{{ ansible_distribution }}-{{ ansible_distribution_release }}"
        state: present
      delegate_to: localhost
      when: ansible_facts['virtualization_role'] == "guest"

