---
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
#       T A Y G E T O S  -  DMZ host
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- name: Playbook to configure the host "taygetos"
  hosts: taygetos
  gather_facts: true


  tasks:

    - include_role:
        name: docker
      vars:
        ansible_become: true   # install as root

    - include_role:
        name: config_portainer_endpoint_create

    - include_role:
        name: config_hostscanner_entry_create

    # - include_role:
    #     name: docker_acme_dns

    - include_role:
        name: docker_traccar


    - name: Add NetBox tags to the virtual machine
      netbox.netbox.netbox_virtual_machine:
        netbox_url: "{{ netbox_api_url }}"
        netbox_token: "{{ netbox_api_token }}"
        data:
          name: "{{ ansible_hostname }}"
          tags: 
          - ansible
          - docker
          - "{{ ansible_distribution }}-{{ ansible_distribution_release }}"
        state: present
      delegate_to: localhost
      when: ansible_facts['virtualization_role'] == "guest"
