---
- name: Playbook to configure the host "dmzserver1"
  hosts: dmzserver1

  # wait with gathering facts until host is up and running
  # fact gathering will be done in role " basic_lxc"
  gather_facts: true


  tasks:

    - include_role:
        name: docker
      vars:
        ansible_become: true   # install as root

    - include_role:
        name: portainer_endpoint_create

    - include_role:
        name: docker_telegraf
