---
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
#       U N I F I
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- name: Playbook to configure the host "unifi"
  hosts: unifi
  gather_facts: true


  tasks:

    - include_role:
        name: docker
      vars:
        ansible_become: true   # install as root

    - include_role:
        name: config_portainer_endpoint_create

    - include_role:
        name: config_hostscanner_entry_create

    - include_role:
        name: docker_unifi
