---
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
#       P I N D O S
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- name: Playbook to configure the host "pindos"
  hosts: pindos
  gather_facts: true

  tasks:

    - include_role:
        name: docker
      vars:
        ansible_become: true   # install as root


    - include_role:
        name: docker_telegraf


    - include_role:
        name: docker_portainer
