---
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
#       N E T B O X (deel 1)
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- name: Playbook to configure the host "netbox"
  hosts: 192.168.55.21
  gather_facts: true


  tasks:

    - include_role:
        name: docker
      vars:
        ansible_become: true   # install as root
