---
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
#       T A Y G E T O S
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- name: Playbook to configure the host "taygetos"
  hosts: taygetos
  gather_facts: true


  vars:
    - zabbix_host_groups:
        - "Linux servers"
        - "Ping only hosts"
        - "LXC containers"

    - zabbix_templates:
        - "ICMP Ping"
        - "Linux by Zabbix agent"


  tasks:

    - include_role:
        name: docker
      vars:
        ansible_become: true   # install as root

    - include_role:
        name: config_portainer_endpoint_create

    - include_role:
        name: config_hostscanner_entry_create

    - include_role:
        name: docker_telegraf

    - include_role:
        name: docker_acme_dns
