---
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
#       N E T B O X (deel 2)
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- name: Playbook to configure the host "netbox"
  hosts: 192.168.55.21
  gather_facts: true


  tasks:

    - name: Install git to clone the netbox repository
      apt:
        name:
          - git
      vars:
        ansible_become: true   # install as root


    - include_role:
        name: docker_netbox
