---
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
#       P I N D O S
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- name: Playbook to configure the host "pindos"
  hosts: pindos
  gather_facts: true

  tasks:

    - include_role:
        name: docker
      vars:
        ansible_become: true   # install as root


    - include_role:
        name: config_hostscanner_entry_create

    - include_role:
        name: docker_portainer

    - include_role:
        name: docker_homepage


    - name: Add NetBox tags to the virtual machine
      netbox.netbox.netbox_virtual_machine:
        netbox_url: "{{ netbox_api_url }}"
        netbox_token: "{{ netbox_api_token }}"
        data:
          name: "{{ ansible_hostname }}"
          tags: 
          - ansible
          - devsys
          - docker
          - "{{ ansible_distribution }}-{{ ansible_distribution_release }}"
        state: present
      delegate_to: localhost
      when: ansible_facts['virtualization_role'] == "guest"
