---
- name: Playbook om een development systeem van alle software en instellingen te voorzien
  hosts: dev
  become: true

  tasks:
    - name: Make sure all packages are up-to-date
      apt:
        upgrade: dist
        update_cache: true


    ###################################################################
    #
    #         Install generic tools
    #
    - name: Installeer algemene ontwikkel tools
      apt:
        name:
          - git
        state: present


    ###################################################################
    #
    #         Install ansible
    #
    - name: Installeer basis requirements voor ansible
      apt:
        name:
          - ansible
          - python3-pip
        state: present

    - name: Installeer ansible test tools
      pip:
        name:
          - yamllint
          - ansible-lint


    ###################################################################
    #
    #         Install Sublime Text editor
    #
    - name: Installeer basis requirements om Sublime repository toe te voegen
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - name: Add Sublime apt-key
      apt_key:
        url: https://download.sublimetext.com/sublimehq-pub.gpg

    - name: Add Sublime repo
      apt_repository:
        repo: deb https://download.sublimetext.com/ apt/stable/

    - name: Install Sublime
      apt:
        name:
          - sublime-text
        state: present
        update_cache: true

