---
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
#       Install docker & docker-compose and registers system with portainer host
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- name: Play to install docker and docker-compose
  hosts: all


  tasks:

    - include_role:
        name: config_dns_entry_delete

    - include_role:
        name: config_portainer_endpoint_delete

    - include_role:
        name: config_hostscanner_entry_delete

    - include_role:
        name: config_netbox_service_delete_all
