---
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
#   Restore a docker volume - run with sudo privileges
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- name: Restore a specific docker volume


  ################################################################
  #
  #     Adust these variables for each individual restore !!
  #
  ################################################################

  hosts: taygetosxx
  vars:
    local_backup_file: "~/backup/taygetos/acme-dns-2022-03-17.tgz"
    volume_folder: "/opt/docker/acme-dns"


  tasks:

    - name: Check whether docker-compose file for container exists
      stat:
        path: "{{ volume_folder }}/docker-compose.yml"
      register: compose


    - name: Stop the container when a docker-compose file exists
      docker_compose:
        project_src: "{{ volume_folder }}"
        state: present
        stopped: true
      when: compose.stat.exists is true


    - name: Delete the existing volume folder and all its content
      file:
        path: "{{ volume_folder }}"
        state: absent
      vars:
        ansible_become: true   # Delete as root to really delete everything


    - name: Restore the backup to the volume directory
      unarchive:
        src: "{{ local_backup_file }}"
        dest: "{{ volume_folder | dirname }}"


    - name: Start the container
      docker_compose:
        project_src: "{{ volume_folder }}"
        state: present
        stopped: false
