---
- name: Test playbook
  hosts:
    - olympos

  vars:
    secrets_dir: "~/.ansible"


  tasks:

    - name: Include secret variables
      ansible.builtin.include_vars:
        file: "{{ secrets_dir }}/secrets.yml"


    - debug:
        #var: ansible_facts
        msg: "Inventory hostname = {{ inventory_hostname }}"
