---
- name: Test playbook
  hosts: rodopi
  gather_facts: true

  tasks:

    - debug:
        #var: ansible_facts
        msg: "Inventory hostname = {{ inventory_hostname }}"

    - debug:
        msg: "ansible user = {{ ansible_user }}"


    - name: execute command
      command: echo ~
      delegate_to: localhost
