---
- name: Test playbook
  hosts: rodopi
  gather_facts: true
  become: true

  tasks:

    - debug:
        #var: ansible_facts
        msg: "Inventory hostname = {{ inventory_hostname }}"

    - debug:
        msg: "ansible user = {{ ansible_user }}"


    - name: Get location of ssh key (required with semaphore)
      command: echo ~
      delegate_to: localhost
      register: command_output
      vars:
        ansible_become: false

    - debug:
        msg: "tilde = |{{ command_output.stdout }}|"

