---
version: "3"

services:

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - /opt/docker/mosquitto:/mosquitto/config
