---
- name: Create directory for persistent volume
  file:
    path: "{{ mosquitto_volume_dir }}"
    state: directory


- name: Copy mosquitto.conf file to remote host
  copy:
    src: "mosquitto.conf"
    dest: "{{ mosquitto_volume_dir }}/mosquitto.conf"


- name: Create docker-compose.yml file from template
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ mosquitto_volume_dir }}/docker-compose.yml"


- name: Bring up the docker stack
  docker_compose:
    project_src: "{{ mosquitto_volume_dir }}"
    state: present


- name: Add mosquitto service to VM config in Netbox
  include_role:
    name: config_netbox_service_create
