---
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
#       Add entry for remote host in hostscanner config
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- name: Load in secrets variables
  include_vars: "vars/secrets.yml"


- name: Load in hostscanner variables
  include_vars: "roles/docker_hostscanner/vars/main.yml"


- name: Add remote host to hostscanner config file
  lineinfile:
    path: "{{ hostscanner_volume_dir }}/{{ hostscanner_config_file }}"
    line: "{{ ansible_default_ipv4.address }}"
  register: lineinfile
  delegate_to: "{{ hostscanner_host }}"


# - name: Restart hostscanner container when configuration file has been changed
#  docker_compose:
#    project_src: "{{ hostscanner_volume_dir }}"
#    services:
#      - hostscanner
#    state: present
#    restarted: true
#  when: lineinfile.changed
#  delegate_to: "{{ hostscanner_host }}"
