---
- name: Load in general docker variables
  include_vars: "vars/docker_general.yml"


- name: Create directories
  file:
    path: "{{ speedtest2influx_volume_dir }}"
    state: directory


- name: Create docker-compose.yml file from template
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ speedtest2influx_volume_dir }}/docker-compose.yml"


- name: Start the docker stack
  docker_compose:
    project_src: "{{ speedtest2influx_volume_dir }}"
    state: present
