---
- name: Create directory for persistent volume 1/2
  file:
    path: "{{ acme_dns_volume_dir }}/config"
    state: directory


- name: Create directory for persistent volume 2/2
  file:
    path: "{{ acme_dns_volume_dir }}/data"
    state: directory


- name: Create docker-compose.yml file from template
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ acme_dns_volume_dir }}/docker-compose.yml"


- name: Start the docker stack
  docker_compose:
    project_src: "{{ acme_dns_volume_dir }}"
    state: present


- name: Add acme-dns services to VM config in Netbox
  include_role:
    name: config_netbox_service_create
