---
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
#   Install packages and backup config files
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- name: Installeer benodigde packages
  apt:
    name:
      - nut
      - nut-server
      - nut-client
      - apache2
      - nut-cgi
    state: present


- name: Create backup folder for original config files
  file:
    path: /etc/nut/original_configs
    state: directory
    mode: '0755'
  register: no_backup_yet


- name: Get a list of all nut "conf" files
  find:
    paths: /etc/nut
    patterns: "*.conf"
  register: files_to_move
  when: no_backup_yet.changed


- name: Move original configs to backup folder
  command: "mv {{ item.path }} /etc/nut/original_configs"
  with_items: "{{ files_to_move.files }}"
  when: files_to_move.files is defined

- name: Move original configs to backup folder
  command: "mv /etc/nut/upsd.users /etc/nut/original_configs"
  when: files_to_move.files is defined


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
#   Create config files from templates and reboot
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- name: Create conf file from all the templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "hosts.conf.j2", dest: "/etc/nut/hosts.conf"}
    - { src: "nut.conf.j2", dest: "/etc/nut/nut.conf"}
    - { src: "ups.conf.j2", dest: "/etc/nut/ups.conf"}
    - { src: "upsd.conf.j2", dest: "/etc/nut/upsd.conf"}
    - { src: "upsd.users.j2", dest: "/etc/nut/upsd.users"}
    - { src: "upsmon.conf.j2", dest: "/etc/nut/upsmon.conf"}
    - { src: "upsset.conf.j2", dest: "/etc/nut/upsset.conf"}
  register: template_create


- name: Reboot remote server after config files have been created
  reboot:
  when: template_create.changed


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
#   Start the NUT CGI Server
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- name: Enable Apache CGI module
  apache2_module:
    name: cgid
    state: present
    ignore_configcheck: true


- name: Restart Apache
  systemd:
    name: apache2
    state: restarted


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
#   Update Netbox administration
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- name: Add NUT server services to machine config in Netbox
  include_role:
    name: config_netbox_service_create
