---
- name: Create directory for persistent volume
  file:
    path: "{{ uptime_kuma_volume_dir }}/data"
    state: directory


- name: Create docker-compose.yml file from template
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ uptime_kuma_volume_dir }}/docker-compose.yml"


- name: Start the docker stack
  docker_compose:
    project_src: "{{ uptime_kuma_volume_dir }}"
    state: present


- name: Add uptime-kuma service to VM config in Netbox
  include_role:
    name: config_netbox_service_create
