---
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
#   Backup a docker volume - volume folder is passed as variable "volume_folder"
#
#       variable "stop_for_backup" defines whether the container is stopped
#       before making a backup or not
#
#       must be called with variable ansible_become = true
#
#       Ansible controller mounts the SMB share ( required for backing up
#       containers on hosts in the DMZ )
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- name: Load in secret variables
  include_vars: "~/.ansible/secrets.yml"


- name: Ensure that the backup root exists on the Ansible controller
  ansible.builtin.file:
    path: "{{ backup_mnt }}"
    state: directory
    mode: '0755'
  delegate_to: localhost


- name: Ensure that the share is mounted on the backup root on the Ansible controller
  ansible.posix.mount:
    src: "{{ backup_share }}"
    path: "{{ backup_mnt }}"
    opts: "rw,username={{ backup_user }},password={{ backup_password }}"
    fstype: cifs
    state: ephemeral
  delegate_to: localhost
  

- name: Define the backup folder
  set_fact:
    backup_folder: "{{ backup_mnt }}/Backup/Docker/{{ ansible_hostname }}"


- name: Ensure that the backup folder exists on the Ansible controller
  ansible.builtin.file:
    path: "{{ backup_folder }}"
    state: directory
    mode: '0755'
  delegate_to: localhost


- name: Define the backup filename
  set_fact:
    backup_file: "{{ volume_folder.split('/') | last }}-{{ ansible_date_time.date }}.tgz"


- name: Stop the container (unless told not to "stop_for_backup = false")
  docker_compose:
    project_src: "{{ compose_folder }}"
    state: present
    stopped: true
  when: stop_for_backup is undefined or stop_for_backup is true


- name: Create backup of the volume directory
  archive:
    path: "{{ volume_folder }}"
    dest: "/tmp/{{ backup_file }}"


- name: Start the container (unless container was not stopped)
  docker_compose:
    project_src: "{{ compose_folder }}"
    state: present
    stopped: false
  when: stop_for_backup is undefined or stop_for_backup is true


- name: Get location of ssh key (required with semaphore)
  command: echo ~
  delegate_to: localhost
  register: command_output


- name: Copy backup from remote host to the backup_share
  command: scp -i {{ command_output.stdout }}/.ssh/id_rsa -o StrictHostKeyChecking=no {{ ansible_user }}@{{ ansible_default_ipv4.address }}:/tmp/{{ backup_file }} {{ backup_folder }}/{{ backup_file }}
  delegate_to: localhost


- name: Delete backup file on remote host
  file:
    path: "/tmp/{{ backup_file }}"
    state: absent
