---
- name: Create directories
  file:
    path: "{{ volume_dir }}"
    state: directory

- name: Create telegraf.conf file from template
  template:
    src: "telegraf.conf.j2"
    dest: "{{ volume_dir }}/telegraf.conf"

- name: Copy docker-compose file to remote host
  copy:
    src: "docker-compose.yml"
    dest: "{{ volume_dir }}/docker-compose.yml"

- name: Bring up the docker stack
  docker_compose:
    project_src: "{{ volume_dir }}"
    state: present
