---
- name: Load in general docker variables
  include_vars: "vars/docker_general.yml"


- name: Create directories
  file:
    path: "{{ telegraf_volume_dir }}"
    state: directory


- name: Create telegraf.conf file from template
  template:
    src: "telegraf.conf.j2"
    dest: "{{ telegraf_volume_dir }}/telegraf.conf"


- name: Create docker-compose.yml file from template
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ telegraf_volume_dir }}/docker-compose.yml"


- name: Start the docker stack
  docker_compose:
    project_src: "{{ telegraf_volume_dir }}"
    state: present
