---
- name: Add influx apt-key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key


- name: Add influx repo
  apt_repository:
    repo: deb https://repos.influxdata.com/debian bullseye stable


- name: Install telegraf
  apt:
    name:
      - telegraf
    state: present
    update_cache: true


- name: Create telegraf.conf file from template
  template:
    src: "telegraf.conf.j2"
    dest: "/etc/telegraf/telegraf.conf"


- name: Restart telegraf
  systemd:
    name: telegraf
    state: restarted
