---
- name: Create directory for persistent volume
  file:
    path: "{{ grafana_volume_dir }}/varlib"
    state: directory


- name: Create docker-compose.yml file from template
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ grafana_volume_dir }}/docker-compose.yml"


- name: Bring up the docker stack
  docker_compose:
    project_src: "{{ grafana_volume_dir }}"
    state: present


- name: Add grafana service to VM config in Netbox
  include_role:
    name: config_netbox_service_create
