---
- name: Create directory for persistent config volume
  file:
    path: "{{ homepage_volume_dir }}/config"
    state: directory


- name: Create directory for persistent images volume
  file:
    path: "{{ homepage_volume_dir }}/images"
    state: directory


- name: Create directory for persistent icons volume
  file:
    path: "{{ homepage_volume_dir }}/icons"
    state: directory


- name: Create docker-compose.yml file from template
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ homepage_volume_dir }}/docker-compose.yml"


- name: Start the docker stack
  docker_compose:
    project_src: "{{ homepage_volume_dir }}"
    state: present


- name: Add homepage service to VM config in Netbox
  include_role:
    name: config_netbox_service_create
